[package]
name = "bb8_cypher"
version = "0.4.0"
license = "MIT"
authors = ["Markus Kohlhase <mail@markus-kohlhase.de>"]
repository = "https://github.com/flosse/r2d2-cypher"
description = "Cypher support for the r2d2 connection pool"
readme = "README.md"

keywords = ["cypher", "neo4j", "r2d2"]

[dependencies]
rusted_cypher = { git = "https://github.com/hobofan/rusted-cypher", rev = '4b68788e33708ea006e087d341685e6c7875ea1d' }
bb8 = "0.3.0"
futures = "0.1.25"
